version: '3'
    
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=news
      - POSTGRES_USER=omar
      - POSTGRES_PASSWORD=010
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000 # gunicorn NewsPaper.wsgi -b 0.0.0.0:8000
    environment: 
      # - SECRET_KEY=ic5s$e!v0k0^!r$#6!w(b%cbgt=%)x@0x9@h7io^(&sg)epc+d
      - DEBUG=1
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    links: 
      - db:db